version: '3.1'

services:
  db:
    image: mysql:8.1.0
    command: 
      --sql-mode=
    volumes:
    - /etc/mysql/my.cnf

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: task_manager
      MYSQL_USER: root

volumes:
  dbbase: